import argparse


def parse_args():
    parser = argparse.ArgumentParser(description="Generate HTK HHEd script and fulllist for state tying.")
    
    parser.add_argument("-m", "--monophones", required=True, help="Path to the monophone list file.")
    parser.add_argument("-q", "--questions", required=True, help="Path to the questions (QS) file.")
    
    parser.add_argument("-s", "--stats", default="stats", help="Name of the stats file generated by HERest (default: stats).")
    parser.add_argument("-t", "--threshold", type=float, default=350.0, help="TB command log-likelihood threshold (default: 350.0).")
    parser.add_argument("-r", "--ro-threshold", type=float, default=100.0, help="RO command outlier threshold (default: 100.0).")
    parser.add_argument("-o", "--output-hed", default="tie.hed", help="Output filename for the HED script (default: tie.hed).")
    parser.add_argument("-l", "--output-fulllist", default="fulllist", help="Output filename for the full triphone list (default: fulllist).")
    parser.add_argument("-L", "--tiedlist-file", default="tiedlist", help="Name of the tiedlist file where HMMs could be tied together (default: tiedlist).")
    parser.add_argument("-T", "--trees-file", default="trees", help="Name of the trees file where questions and trees are saved to (default: trees).")
    parser.add_argument("-c", "--ci-phones", default="sil,sp", help="Comma-separated list of Context Independent phones to exclude from tying (default: sil,sp).")
    
    return parser.parse_args()


def load_phones(filename):
    try:
        with open(filename, 'r') as f:
            return [line.strip() for line in f if line.strip()]
    except FileNotFoundError:
        print(f"Error: Monophone file '{filename}' not found.")
        return []


def generate_fulllist(phones, ci_phones):
    triphones = []
    print("Generating fulllist...")
    for ci in ci_phones:
        triphones.append(ci)
    for left in phones:
        for center in phones:
            if center in ci_phones:
                continue
            if center == left:
                continue
            biphone = f"{left}-{center}"
            triphones.append(biphone)
            for right in phones:
                if center == right:
                    continue
                triphone = f"{left}-{center}+{right}"
                triphones.append(triphone)
    for center in phones:
        if center in ci_phones:
            continue
        triphones.append(center)
        for right in phones:
            if center == right:
                continue
            biphone = f"{center}+{right}"
            triphones.append(biphone)
    return triphones


def write_hed(args, phones, ci_phones):
    emitting_states = [2, 3, 4] 
    
    with open(args.output_hed, 'w') as f:
        f.write(f'RO {args.ro_threshold} "{args.stats}"\n')
        f.write('TR 0\n\n')
        
        try:
            with open(args.questions, 'r') as qf:
                f.write(qf.read())
        except FileNotFoundError:
            print(f"Error: Questions file '{args.questions}' not found.")
            return
        f.write('\n\n')
        
        # f.write('# --- Tree Build Commands ---\n')
        f.write('TR 2\n') 
        
        for p in phones:
            if p in ci_phones:
                continue 
            
            for state in emitting_states:
                macro_name = f"{p}_s{state}"
                component_list = f'("{p}","*-{p}+*","{p}+*","*-{p}")'
                
                cmd = f'TB {args.threshold} "{macro_name}" {{{component_list}.state[{state}]}}\n'
                f.write(cmd)
        
        f.write('\n')
        
        # f.write('# --- Finalize ---\n')
        f.write('TR 1\n')
        f.write(f'AU "{args.output_fulllist}"\n')
        f.write(f'CO "{args.tiedlist_file}"\n')
        f.write(f'ST "{args.trees_file}"\n')


def main():
    args = parse_args()
    
    ci_phones_set = set(args.ci_phones.split(','))
    
    phones = load_phones(args.monophones)
    
    full_triphones = generate_fulllist(phones, ci_phones_set)
    
    with open(args.output_fulllist, 'w') as f:
        for tp in full_triphones:
            f.write(tp + '\n')
    print(f"Wrote {len(full_triphones)} triphones to '{args.output_fulllist}'")

    write_hed(args, phones, ci_phones_set)
    print(f"Successfully generated '{args.output_hed}' with threshold {args.threshold}")


if __name__ == "__main__":
    main()
